[wiki]
language = "ru"       # Язык Википедии (en, ru, fr и т.д.)
max_iterations = 1_000_000 # Максимальное количество шагов поиска
pllimit = 10000         # Лимит ссылок в запросе
lhlimit = 10000         # Лимит обратных ссылок в запросе
using_date = true # Использоветь даты